description: Projeto destinado para criar projetos de automações de back-end usando Kotlin/Java e rest assured.
name: stack-rest-assured
display-name: stack-rest-assured
picture: restassured.png
category: backend
compatibility:
  - Java
  - Kotlin
technologies:
  - Java
  - Kotlin
about: docs/about.md
use-cases:
  - title: Como usar
    content: docs/use-case.md
    stackfile: stackfiles/default.yaml
